import type { HistoricalNode } from "../store/useExperienceStore";


export interface CausalSection {
  id: string;
  title: string;
  content: string;
}

export interface Citation {
  id: string;
  label: string;
  nodeId: string;
}

// Highly detailed, world-class historian level causal explanations for all 11 nodes.
// Each section contains rich, thoughtful historical causality, integrated with citation tags.
// Citation tags are formatted as: [label](citation:nodeId)
const historicalCausalDb: Record<string, CausalSection[]> = {
  agricultural_revolution: [
    {
      id: "root_causes",
      title: "Root Causes",
      content: "The transition to agriculture was not a sudden choice, but a pressure-driven response to the end of the last glacial maximum around 10,000 BCE. As global temperatures rose and large-game species dwindled, human bands faced a critical food crisis. In fertile river valleys like the Fertile Crescent, wild grains like wheat and barley flourished. Humans began protecting these patches, leading to deliberate cultivation. This ecological shift was accompanied by the domestication of animals, establishing the first feedback loop of human-directed selective breeding."
    },
    {
      id: "immediate_effects",
      title: "Immediate Effects",
      content: "For the first time, human groups transitioned from nomadic lifestyles to permanent agrarian settlements. This sedentary life triggered a population explosion, as agricultural surpluses could feed more children than hunter-gatherer foraging. However, it also brought severe trade-offs: early farmers suffered from narrower diets, higher rates of infectious diseases due to close proximity to domesticated livestock, and the introduction of intensive, repetitive physical labor."
    },
    {
      id: "long_term_effects",
      title: "Long-Term Effects",
      content: "Surplus grain required storage, defense, and management, which directly catalyzed the [Rise of Cities](citation:rise_of_cities). With food secured by a portion of the population, others could specialize in pottery, metallurgy, and administration. This division of labor laid the groundwork for social hierarchies, centralized political power, and institutionalized gender inequalities as land ownership became the primary measure of security and wealth."
    },
    {
      id: "unexpected_consequences",
      title: "Unexpected Consequences",
      content: "The domestication of plants and animals effectively domesticated humans as well. Rather than owning the land, humans became bound to its rigid seasonal cycles, laboring far longer hours than their nomadic ancestors. Furthermore, the concentrated storage of grain made early settlements highly vulnerable to catastrophic pests, crop failures, and targeted raids by nomadic groups, inventing the concept of siege warfare and defensive fortifications."
    },
    {
      id: "hidden_connections",
      title: "Hidden Connections",
      content: "The mathematical necessity of tracking grain storage, measuring land boundaries, and predicting seasonal flooding led directly to the invention of geometry, calendar systems, and early bookkeeping, which would later evolve into the first [Cuneiform & Writing Systems](citation:writing_system)."
    },
    {
      id: "modern_impact",
      title: "Modern Impact",
      content: "Modern industrial agriculture, global food supply chains, and the planetary ecological crises of the Anthropocene—ranging from massive soil degradation to runaway carbon emissions—all trace their lineage back to this initial, fundamental decision to actively modify and control the earth's biosphere."
    }
  ],
  rise_of_cities: [
    {
      id: "root_causes",
      title: "Root Causes",
      content: "Urbanization arose from the fertile alluvial plains of Mesopotamia (specifically Sumer) and Egypt around 4500 BCE. The primary catalyst was the agricultural surplus generated by the [Agricultural Revolution](citation:agricultural_revolution). To maximize crop yields in arid zones, communities had to construct and maintain massive, complex irrigation systems. This required high-level collective coordination, leading populations to cluster around administrative temples and central storehouses."
    },
    {
      id: "immediate_effects",
      title: "Immediate Effects",
      content: "Cities transformed human geography, concentrating thousands of unrelated individuals into dense, structured environments. This spatial concentration accelerated cultural exchange, technological innovation, and economic trade. However, it also gave rise to rigid class structures, centralized priesthoods, and early military classes tasked with protecting urban wealth from external threats."
    },
    {
      id: "long_term_effects",
      title: "Long-Term Effects",
      content: "The administrative demands of urban taxation, resource distribution, and legal disputes led directly to the codification of laws, seen clearly in the [Code of Hammurabi](citation:code_of_hammurabi). Cities became the engines of empires, projecting military and economic power over vast hinterlands and establishing the urban-rural divide that has characterized civilization ever since."
    },
    {
      id: "unexpected_consequences",
      title: "Unexpected Consequences",
      content: "The extreme density of early cities, coupled with rudimentary sanitation, turned them into demographic sinks. Infectious diseases—many jumped from livestock—frequently decimated urban populations, meaning early cities could only sustain their numbers by continuously drawing in migrants from rural areas. In essence, cities were biological hazards that survived only through economic magnetism."
    },
    {
      id: "hidden_connections",
      title: "Hidden Connections",
      content: "The dense social friction of urban marketplaces necessitated standardized systems of weights, measures, and currency, which in turn forced the evolution of abstract mathematical thinking and formal writing to replace oral trust."
    },
    {
      id: "modern_impact",
      title: "Modern Impact",
      content: "Today, for the first time in history, over 55% of the global population resides in cities, with megacities serving as the primary nodes of global capital, culture, and carbon consumption, continuing the Sumerian model of high-density resource aggregation."
    }
  ],
  writing_system: [
    {
      id: "root_causes",
      title: "Root Causes",
      content: "Writing was not invented to record poetry or philosophy, but to solve a crisis of administrative scale. By 3400 BCE, the complex temple economies of Sumerian cities like Uruk had grown too large for human memory. Priests needed an infallible way to record grain tributes, temple lands, and labor rations. Writing emerged as a system of clay tokens, which gradually evolved into pictographs pressed into soft clay with reed styluses, eventually abstracting into cuneiform."
    },
    {
      id: "immediate_effects",
      title: "Immediate Effects",
      content: "The invention of writing created a highly influential class of scribes who held a monopoly on state administration, taxation, and legal affairs. It externalized human memory, allowing transactions to be verified across time and space without relying on fallible oral testimony, instantly stabilizing long-distance commerce."
    },
    {
      id: "long_term_effects",
      title: "Long-Term Effects",
      content: "Writing decoupled knowledge from individual human lifetimes, enabling cumulative cultural evolution. Generations could now read, critique, and build upon the exact thoughts of dead ancestors. This cognitive leap eventually enabled the preservation of early science, the distribution of laws like the [Code of Hammurabi](citation:code_of_hammurabi), and centuries later, the rapid dissemination of ideas via the [Gutenberg Printing Press](citation:printing_press)."
    },
    {
      id: "unexpected_consequences",
      title: "Unexpected Consequences",
      content: "Writing fundamentally restructured human consciousness. It shifted the dominant sensory mode of high culture from auditory-participatory to visual-analytic, fostering a more detached, objective, and linear way of thinking. It also created the first 'information divide,' separating literate elites from illiterate masses who were systematically excluded from governance."
    },
    {
      id: "hidden_connections",
      title: "Hidden Connections",
      content: "The physical medium of writing shaped political structures. Civilizations that relied on heavy clay tablets (Mesopotamia) tended to remain localized and centralized, while those that adopted light, portable papyrus (Egypt) could easily transmit administrative orders across vast distances, enabling the governance of sprawling territorial empires."
    },
    {
      id: "modern_impact",
      title: "Modern Impact",
      content: "All modern software, database architectures, and [Artificial Intelligence](citation:artificial_intelligence) systems are the ultimate abstractions of writing. Coding is simply the execution of written instructions, proving that we still live in an infrastructure built entirely on the externalization of thought."
    }
  ],
  code_of_hammurabi: [
    {
      id: "root_causes",
      title: "Root Causes",
      content: "Around 1750 BCE, King Hammurabi of Babylon conquered Mesopotamia, unifying a highly diverse empire of formerly independent city-states. To consolidate his rule and prevent civil fragmentation, he needed to establish a singular, standardized legal framework. By engraving 282 laws onto a massive black basalt stele, he bypassed local customs and tribal allegiances, asserting a supreme, divine mandate from the sun god Shamash."
    },
    {
      id: "immediate_effects",
      title: "Immediate Effects",
      content: "The code established the principle that law was public, objective, and immutable. Written law meant that judges could no longer rule arbitrarily based on personal whim or local bribery, as any citizen could read the stele (or have it read aloud). However, the code was deeply stratified, explicitly prescribing different punishments based on the social class and gender of the victim and perpetrator."
    },
    {
      id: "long_term_effects",
      title: "Long-Term Effects",
      content: "Hammurabi's code popularized the concept of 'lex talionis' (an eye for an eye), which sought to limit endless blood feuds by matching the punishment precisely to the crime. This codification served as a model for subsequent Mediterranean legal traditions, heavily influencing Roman law and, ultimately, the constitutional systems of the West."
    },
    {
      id: "unexpected_consequences",
      title: "Unexpected Consequences",
      content: "By codifying harsh class divisions into law, the state actively institutionalized systemic inequality. Slavery, patriarchal authority, and the commodification of women were no longer merely social habits; they became legal obligations enforced by the threat of state violence, cementing these hierarchies for millennia."
    },
    {
      id: "hidden_connections",
      title: "Hidden Connections",
      content: "The public placement of the stele acted as an early form of state propaganda. It was a physical manifestation of the state's monopoly on violence, teaching citizens to associate the abstract concept of justice with the physical person of the monarch."
    },
    {
      id: "modern_impact",
      title: "Modern Impact",
      content: "Modern statutory law, public legal transparency, and the fundamental constitutional premise that a government must rule by pre-established, public laws rather than arbitrary decrees are direct evolutions of this Babylonian experiment."
    }
  ],
  democratic_foundation: [
    {
      id: "root_causes",
      title: "Root Causes",
      content: "Athenian democracy was born out of intense social friction. By the late 6th century BCE, Athens was on the brink of civil war due to severe wealth inequality, debt slavery, and aristocratic monopolies. In 508 BCE, Cleisthenes, an aristocrat facing political defeat, did something radical: he appealed directly to the common people (the 'demos') for support, introducing sweeping reforms that restructured Athenian citizens into ten cross-cutting tribes to break noble power bases."
    },
    {
      id: "immediate_effects",
      title: "Immediate Effects",
      content: "The reforms created the Assembly ('Ekklesia'), where all free male citizens had an equal vote on state policy, war, and law. It introduced sortition (random lottery) to select government officials rather than elections, which they believed favored the rich. It also established ostracism—a yearly vote to exile any citizen deemed too powerful or ambitious—protecting the democracy from tyranny."
    },
    {
      id: "long_term_effects",
      title: "Long-Term Effects",
      content: "Athenian democracy proved that a complex, powerful state could govern itself without a monarch or hereditary nobility. It fostered an unprecedented explosion in philosophy, rhetoric, theater, and history, as citizens had to debate and persuade their peers. Centuries later, these ideals were rediscovered during the [Enlightenment](citation:enlightenment), serving as the intellectual inspiration for the American and French Revolutions."
    },
    {
      id: "unexpected_consequences",
      title: "Unexpected Consequences",
      content: "Athenian democracy was highly exclusive and relied on extreme exploitation. It was built entirely on a foundation of chattel slavery and the absolute exclusion of women and foreign residents. Furthermore, direct democracy proved highly vulnerable to demagogues; the assembly was easily swayed by emotional rhetoric, leading to catastrophic military decisions like the Sicilian Expedition and the execution of Socrates."
    },
    {
      id: "hidden_connections",
      title: "Hidden Connections",
      content: "The intense demand for persuasive speech in democratic courts and the assembly created the Sophist movement, which pioneered formal logic and linguistic analysis, laying the groundwork for Western philosophy."
    },
    {
      id: "modern_impact",
      title: "Modern Impact",
      content: "Modern representative democracies, civic voting rights, and the ongoing tension between populist demagoguery and institutional stability are direct continuations of the political trials first debated on the rocky hill of the Pnyx in Athens."
    }
  ],
  printing_press: [
    {
      id: "root_causes",
      title: "Root Causes",
      content: "The printing press emerged from a confluence of socio-economic and technological factors in mid-15th century Germany. Johannes Gutenberg did not invent printing; instead, he synthesized existing technologies. He adapted the heavy wooden screw press used in winemaking, formulated durable oil-based inks that would adhere to metal, and engineered a precise alloy of lead, tin, and antimony that melted at low temperatures but cooled into highly durable, precise movable type."
    },
    {
      id: "immediate_effects",
      title: "Immediate Effects",
      content: "The immediate effect was an unprecedented collapse in the cost of information. Books, which previously took scribes months to copy by hand on expensive parchment, could now be produced in thousands of copies on cheap paper within days. Literacy rates skyrocketed. The Catholic Church's monopoly over scripture was shattered, as the rapid printing of Martin Luther's German translation of the Bible ignited the Protestant Reformation, plunging Europe into decades of religious warfare."
    },
    {
      id: "long_term_effects",
      title: "Long-Term Effects",
      content: "By standardizing and multiplying texts, the printing press laid the cognitive foundation for the [Scientific Revolution](citation:scientific_revolution). Scientists could now publish diagrams and data that were guaranteed to be identical in every copy, enabling international collaboration and empirical peer review. It also nurtured [The Enlightenment](citation:enlightenment) by creating a public sphere of salons, pamphlets, and newspapers where ideas could be debated outside royal control."
    },
    {
      id: "unexpected_consequences",
      title: "Unexpected Consequences",
      content: "The printing press acted as a major catalyst for modern nationalism. To maximize profits, printers stopped publishing in Latin and began printing in local vernaculars (German, French, English). This standardized regional dialects, creating shared national identities that eventually led to the collapse of multinational empires and the rise of modern nation-states. Additionally, the sudden shift from an oral-auditory culture to a visually intensive literate culture led to a massive, widespread increase in myopia (nearsightedness) across Europe."
    },
    {
      id: "hidden_connections",
      title: "Hidden Connections",
      content: "The mechanical standardization of identical, interchangeable lead letters was the direct ancestor of industrial manufacturing. Gutenberg's punch-cutting and casting methods pioneered the precise metallurgical techniques that would later build the machines of the [Industrial Revolution](citation:industrial_revolution)."
    },
    {
      id: "modern_impact",
      title: "Modern Impact",
      content: "The internet, social media networks, and the current democratization and fragmentation of truth are direct echoes of the printing press's early history. We are experiencing the same structural tension between centralized gatekeepers and decentralized, viral information flows that Europe faced in the 1500s."
    }
  ],
  scientific_revolution: [
    {
      id: "root_causes",
      title: "Root Causes",
      content: "The Scientific Revolution was sparked by the rediscovery of classical texts, the spread of printing, and the geographic discoveries of the 15th and 16th centuries. When explorers found entire continents unmentioned in ancient texts or scripture, the absolute authority of classical knowledge shattered. Scholars realized they had to observe the world directly. This empirical push was supercharged by the [Gutenberg Printing Press](citation:printing_press), which allowed mathematical formulas, astronomical tables, and anatomical diagrams to be distributed without copying errors."
    },
    {
      id: "immediate_effects",
      title: "Immediate Effects",
      content: "The revolution overthrew the geocentric Aristotelian-Ptolemaic universe, replacing it with Copernicus's heliocentric model, validated by Galileo's telescope and Kepler's mathematics. It established the scientific method—prioritizing mathematical description, systematic experimentation, and empirical observation over philosophical speculation and theological dogma."
    },
    {
      id: "long_term_effects",
      title: "Long-Term Effects",
      content: "This cognitive shift culminated in Newton's mechanics, which proved that the same mathematical laws governed both the heavens and the earth. By demystifying the cosmos, it paved the way for [The Enlightenment](citation:enlightenment), which applied scientific skepticism to human institutions, and the [Industrial Revolution](citation:industrial_revolution), which applied mechanical physics to practical manufacturing."
    },
    {
      id: "unexpected_consequences",
      title: "Unexpected Consequences",
      content: "The mechanization of nature led to a profound disenchantment of the world. Nature was no longer viewed as a living, sacred organism, but as a giant, indifferent clockwork machine. This conceptual shift removed moral barriers to the aggressive exploitation of natural resources, laying the philosophical foundation for the modern ecological crisis."
    },
    {
      id: "hidden_connections",
      title: "Hidden Connections",
      content: "The development of precise glass lenses for telescopes and microscopes was heavily driven by the Dutch spectacle industry. This practical craft directly enabled the theoretical breakthroughs of astronomy and microbiology, showing how high science relies on low craftsmanship."
    },
    {
      id: "modern_impact",
      title: "Modern Impact",
      content: "Every facet of modern technology, medicine, and our ability to manipulate the physical world—up to gene editing and quantum computing—rests entirely on the empirical epistemology established during this intellectual pivot."
    }
  ],
  enlightenment: [
    {
      id: "root_causes",
      title: "Root Causes",
      content: "The Enlightenment was the direct philosophical child of the [Scientific Revolution](citation:scientific_revolution). Having witnessed the power of reason and mathematics to decode the physical universe, thinkers like John Locke and Voltaire argued that the same analytical tools should be applied to human societies, laws, and governments. They sought to dismantle the dogmatic religious authority and absolute monarchies that had drenched Europe in blood during the religious wars of the preceding century."
    },
    {
      id: "immediate_effects",
      title: "Immediate Effects",
      content: "The movement popularized radical concepts: individual liberty, religious tolerance, freedom of speech, and the social contract—the idea that governments derive their legitimacy solely from the consent of the governed. It fostered a vibrant intellectual culture of salons, coffeehouses, and massive collaborative projects like Diderot's Encyclopédie."
    },
    {
      id: "long_term_effects",
      title: "Long-Term Effects",
      content: "Enlightenment philosophy acted as the explosive charge that detonated the Atlantic Revolutions, directly shaping the declaration of independence in America and the overthrow of the monarchy in France. Its ideals formed the bedrock of modern liberal democracies, introducing the separation of powers, secular governance, and universal human rights."
    },
    {
      id: "unexpected_consequences",
      title: "Unexpected Consequences",
      content: "The absolute elevation of reason and categorization had a dark side. It was used by European thinkers to construct highly structured, pseudoscientific racial hierarchies to justify colonial domination, imperialism, and transatlantic slavery, arguing that non-European societies lacked the 'rational capacity' for self-governance."
    },
    {
      id: "hidden_connections",
      title: "Hidden Connections",
      content: "The rise of coffee consumption in 18th-century Europe, replacing beer and wine as the daily beverage of choice for intellectuals, created a sober, caffeinated environment in urban coffeehouses that directly accelerated intense, rational political debate."
    },
    {
      id: "modern_impact",
      title: "Modern Impact",
      content: "Our current debates over free speech, democratic erosion, human rights, and the role of science in public policy are fought entirely on the ideological battlefield mapped out by Enlightenment philosophers three centuries ago."
    }
  ],
  industrial_revolution: [
    {
      id: "root_causes",
      title: "Root Causes",
      content: "The Industrial Revolution was ignited in 18th-century Britain by a unique combination of geology and economics. Britain sat on vast, easily accessible deposits of coal, located close to water transport. Concurrently, Britain had the highest wages in the world, giving manufacturers a powerful economic incentive to substitute expensive human labor with coal-powered machinery, utilizing the thermodynamic breakthroughs of the [Scientific Revolution](citation:scientific_revolution)."
    },
    {
      id: "immediate_effects",
      title: "Immediate Effects",
      content: "The introduction of the steam engine transformed manufacturing and transport, replacing muscle and wind power with fossil fuels. It triggered massive, rapid urbanization as millions of peasants left the countryside to labor in urban factories. This created the modern working class, marked by harsh factory discipline, child labor, and extreme urban pollution."
    },
    {
      id: "long_term_effects",
      title: "Long-Term Effects",
      content: "Industrialization generated unprecedented material wealth, leading to the rise of global capitalism, railways, steamships, and mass consumerism. It reshaped geopolitics, enabling industrialized Western nations to establish vast colonial empires. Ultimately, the high-speed production and computation demands of industrial systems led directly to the [Digital Revolution](citation:digital_revolution)."
    },
    {
      id: "unexpected_consequences",
      title: "Unexpected Consequences",
      content: "By unlocking the concentrated energy of fossil fuels, the Industrial Revolution initiated the Anthropocene—the current geological epoch where human activity dominates the earth's ecosystems. It triggered runaway carbon dioxide accumulation, initiating global climate change, and created the modern microplastic and chemical pollution crises."
    },
    {
      id: "hidden_connections",
      title: "Hidden Connections",
      content: "The mechanical synchronization of railways to prevent head-on collisions forced the invention of standardized time zones, destroying local solar time and binding the human species to the artificial, precise ticking of a synchronized global clock."
    },
    {
      id: "modern_impact",
      title: "Modern Impact",
      content: "Our modern daily lives—from the fossil-fuel grids powering our cities to the capitalist structures of work and the looming threat of climate collapse—are entirely structured by the thermodynamic engines built in the 1700s."
    }
  ],
  digital_revolution: [
    {
      id: "root_causes",
      title: "Root Causes",
      content: "The Digital Revolution was forged in the fires of World War II and the Cold War. The military needed rapid, automated calculations for ballistics and cryptography, driving the creation of the first electronic computers. This research was supercharged by the invention of the silicon transistor at Bell Labs in 1947, which allowed vacuum tubes to be replaced by solid-state electronics, initiating the exponential scaling of computing power known as Moore's Law."
    },
    {
      id: "immediate_effects",
      title: "Immediate Effects",
      content: "The transition from analog to digital information rewired global telecommunications. The creation of microprocessors and the launch of the internet (ARPANET in 1969) democratized computation, turning computers from massive mainframe tools of states and corporations into personal consumer devices, linking humanity into a singular, instant information network."
    },
    {
      id: "long_term_effects",
      title: "Long-Term Effects",
      content: "Digitization demolished traditional brick-and-mortar industries, replaced paper records with instant databases, and birthed global tech giants. It shifted the primary resource of the global economy from physical oil to abstract data. This massive accumulation of digital data and processing power provided the fertile soil required for the rise of modern [Artificial Intelligence](citation:artificial_intelligence)."
    },
    {
      id: "unexpected_consequences",
      title: "Unexpected Consequences",
      content: "The democratization of information led to the collapse of traditional journalism and shared social realities, giving rise to algorithmic echo chambers, surveillance capitalism, and high-precision digital manipulation. It also created the 'digital panopticon,' where governments and corporations track, store, and monetize every click, search, and movement of global citizens."
    },
    {
      id: "hidden_connections",
      title: "Hidden Connections",
      content: "The mathematical theories behind digital packets—breaking data into tiny fragments, sending them across multiple routes, and reassembling them—were originally designed to ensure communications could survive a nuclear strike, shaping the decentralized, resilient architecture of our modern internet."
    },
    {
      id: "modern_impact",
      title: "Modern Impact",
      content: "We live in an era where software mediates human relationships, finance, politics, and self-identity, proving that reality is now filtered through a digital layer of binary code."
    }
  ],
  artificial_intelligence: [
    {
      id: "root_causes",
      title: "Root Causes",
      content: "Artificial Intelligence arose from the mathematical dreams of Alan Turing and the practical success of the [Digital Revolution](citation:digital_revolution). For decades, AI research languished in 'winters' due to limited computing power. The breakthrough came in the 2010s with the convergence of massive digital datasets (big data generated by the internet) and highly parallelized graphic processing units (GPUs) originally designed for video games, enabling the practical training of deep neural networks."
    },
    {
      id: "immediate_effects",
      title: "Immediate Effects",
      content: "The rapid emergence of generative models and large language models has disrupted knowledge work, programming, artistic creation, and education. It has automated complex cognitive tasks, forcing humanity to confront the reality of non-human entities displaying highly sophisticated linguistic, logical, and creative intelligence."
    },
    {
      id: "long_term_effects",
      title: "Long-Term Effects",
      content: "In the long term, AI threatens to decouple productivity from human labor, reshaping the global capitalist economy and raising profound questions about the future of employment and human purpose. It promises to accelerate scientific discovery—decoding proteins, inventing new materials, and optimizing energy grids—at speeds impossible for human minds."
    },
    {
      id: "unexpected_consequences",
      title: "Unexpected Consequences",
      content: "The flood of highly convincing, AI-generated synthetic media is eroding the concept of objective reality, making it impossible to trust digital audio, video, or text. Furthermore, the massive carbon footprint and water consumption of AI data centers are creating a new, severe environmental crisis, conflicting directly with the physical limits of our planet."
    },
    {
      id: "hidden_connections",
      title: "Hidden Connections",
      content: "The structural architecture of artificial neural networks is loosely inspired by human neurobiology, yet their inner workings remain a 'black box'—highly advanced mathematical systems that produce correct results through statistical associations that their own creators cannot fully explain."
    },
    {
      id: "modern_impact",
      title: "Modern Impact",
      content: "As we stand on the precipice of artificial general intelligence, humanity is, for the first time, actively co-evolving with an autonomous, rapidly accelerating cognitive force, marking the ultimate boundary of our historical timeline."
    }
  ]
};

// Simulated streaming delay helper
const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export interface ExplanationChunk {
  text: string;
  isDone: boolean;
  sectionIndex?: number;
  paragraphIndex?: number;
}

/**
 * Service that handles streaming AI-generated causal explanations.
 * It simulates a highly sophisticated streaming RAG or LLM connection.
 * Supports plugging in OpenAI or a local inference server easily.
 */
export const aiExplanationService = {
  /**
   * Streams a causal explanation for a historical event node.
   * If custom API settings are configured, this can connect to external services.
   * Otherwise, it streams our high-fidelity pre-crafted scholarly text.
   */
  streamExplanation(
    node: HistoricalNode,
    onChunk: (chunk: ExplanationChunk) => void,
    options?: {
      provider?: "mock" | "openai" | "local";
      apiKey?: string;
      localUrl?: string;
    }
  ): () => void {
    let active = true;
    const provider = options?.provider || "mock";

    const executeStream = async () => {
      // 1. Loading Phase: Simulate initial API connection and RAG retrieval
      await sleep(1200);
      if (!active) return;

      // 2. Fallback check: if the node is not in our pre-crafted database, generate a high-quality procedural response
      const sections = historicalCausalDb[node.id] || this.generateProceduralCausalDb(node);

      if (provider === "openai" && options?.apiKey) {
        // Future actual OpenAI Streaming Integration Placeholder
        // We implement a fully compliant OpenAI streaming loop that falls back to mock if it fails
        try {
          const response = await fetch("https://api.openai.com/v1/chat/completions", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${options.apiKey}`
            },
            body: JSON.stringify({
              model: "gpt-4o-mini",
              messages: [
                {
                  role: "system",
                  content: "You are a world-class causal historian. Analyze the following event. Provide an extremely insightful analysis focused on deep historical causality rather than simple summaries. Divide your response into exactly six sections: Root Causes, Immediate Effects, Long-Term Effects, Unexpected Consequences, Hidden Connections, Modern Impact. Use citation syntax like [Related Event](citation:related_node_id) where appropriate to link to other historical events."
                },
                {
                  role: "user",
                  content: `Analyze the event: "${node.title}" (${node.date}). Summary: ${node.description}. Historical Context: ${node.historicalContext}.`
                }
              ],
              stream: true
            })
          });

          if (!response.ok) throw new Error("OpenAI API call failed");
          const reader = response.body?.getReader();
          const decoder = new TextDecoder("utf-8");
          if (!reader) throw new Error("No reader available");

          let buffer = "";
          while (true) {
            const { value, done } = await reader.read();
            if (done || !active) break;

            const chunkStr = decoder.decode(value, { stream: true });
            buffer += chunkStr;

            const lines = buffer.split("\n");
            buffer = lines.pop() || "";

            for (const line of lines) {
              const cleaned = line.replace(/^data: /, "").trim();
              if (cleaned === "[DONE]") continue;
              if (!cleaned) continue;

              try {
                const parsed = JSON.parse(cleaned);
                const content = parsed.choices[0]?.delta?.content || "";
                if (content) {
                  onChunk({ text: content, isDone: false });
                  await sleep(25); // Pace the streaming slightly for premium reading feel
                }
              } catch (e) {
                // Ignore parse errors on incomplete chunks
              }
            }
          }
          onChunk({ text: "", isDone: true });
          return;
        } catch (err) {
          console.warn("OpenAI integration failed, falling back to local scholarly DB: ", err);
        }
      } else if (provider === "local") {
        // Future actual Local Ollama/Llama.cpp Streaming Integration Placeholder
        const endpoint = options?.localUrl || "http://localhost:11434/api/generate";
        try {
          const response = await fetch(endpoint, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              model: "llama3",
              prompt: `Analyze the causality of "${node.title}" divided into Root Causes, Immediate Effects, Long-Term Effects, Unexpected Consequences, Hidden Connections, Modern Impact.`,
              stream: true
            })
          });

          if (!response.ok) throw new Error("Local inference failed");
          const reader = response.body?.getReader();
          const decoder = new TextDecoder("utf-8");
          if (!reader) throw new Error("No reader");

          while (true) {
            const { value, done } = await reader.read();
            if (done || !active) break;
            const text = decoder.decode(value);
            // Ollama streams JSON lines
            const lines = text.split("\n");
            for (const line of lines) {
              if (!line.trim()) continue;
              try {
                const parsed = JSON.parse(line);
                if (parsed.response) {
                  onChunk({ text: parsed.response, isDone: false });
                  await sleep(20);
                }
              } catch {}
            }
          }
          onChunk({ text: "", isDone: true });
          return;
        } catch (err) {
          console.warn("Local inference failed, falling back to local scholarly DB: ", err);
        }
      }

      // Default premium mock streaming behavior:
      // Streams our highly curated scholarly text block-by-block, section-by-section.
      // This guarantees an amazing out-of-the-box experience with world-class writing.
      for (let sIdx = 0; sIdx < sections.length; sIdx++) {
        if (!active) return;
        const section = sections[sIdx];

        // Emit the start of a section
        onChunk({
          text: `##SECTION_START##${section.id}##${section.title}##`,
          isDone: false,
          sectionIndex: sIdx
        });

        // Stream the paragraph content character by character or word by word
        const words = section.content.split(" ");
        let currentStreamed = "";

        // Stream words in small groupings for smooth, steady text flowing
        for (let wIdx = 0; wIdx < words.length; wIdx++) {
          if (!active) return;
          const word = words[wIdx];
          const spacing = wIdx === 0 ? "" : " ";
          currentStreamed += spacing + word;

          onChunk({
            text: currentStreamed,
            isDone: false,
            sectionIndex: sIdx,
            paragraphIndex: 0
          });

          // Delay to simulate human-speed real-time typing of a high-quality summary (around 20-35ms per word)
          const delay = 15 + Math.random() * 20;
          await sleep(delay);
        }

        // Emit the end of a section
        onChunk({
          text: `##SECTION_END##${section.id}##`,
          isDone: false,
          sectionIndex: sIdx
        });

        // Add a slight reflective pause between sections to emphasize progressive discovery
        await sleep(400);
      }

      // Final complete signal
      if (active) {
        onChunk({ text: "", isDone: true });
      }
    };

    executeStream();

    // Return cancellation function to avoid memory leaks or overlapping streams when switching nodes
    return () => {
      active = false;
    };
  },

  /**
   * Generates a high-quality procedural explanation for any custom node not in our database.
   * Leverages the node's fields to write a convincing, structured analysis.
   */
  generateProceduralCausalDb(node: HistoricalNode): CausalSection[] {
    const influenceText = node.influenceScore > 85 ? "a monumental pivot" : "a highly significant anchor";
    
    // Attempt to link a cause and consequence in the text if they exist
    const causeLink = node.incomingCauses.length > 0 
      ? `This was directly precipitated by developments in the [${node.incomingCauses[0]}](citation:${node.incomingCauses[0]}).`
      : "";
    const consequenceLink = node.outgoingConsequences.length > 0
      ? `This eventually paved the path for the [${node.outgoingConsequences[0]}](citation:${node.outgoingConsequences[0]}).`
      : "";

    return [
      {
        id: "root_causes",
        title: "Root Causes",
        content: `The emergence of "${node.title}" in ${node.date} was driven by deep structural currents. Rather than an isolated incident, it represents the crystallization of ongoing systemic tensions. ${node.historicalContext} ${causeLink}`
      },
      {
        id: "immediate_effects",
        title: "Immediate Effects",
        content: `Upon its occurrence, the immediate impact reverberated across the region. It shattered existing paradigms, creating new administrative, social, or technical realities. The immediate summary of this transformation lies in its ability to: ${node.description}`
      },
      {
        id: "long_term_effects",
        title: "Long-Term Effects",
        content: `In the long term, this event became ${influenceText} in the thread of civilization. It established permanent structural pathways, redefining social expectations, technical capabilities, or territorial borders. ${consequenceLink}`
      },
      {
        id: "unexpected_consequences",
        title: "Unexpected Consequences",
        content: `Beyond the intended actions, the event triggered chaotic, secondary feedback loops. Complex historical systems are inherently unpredictable, and this event resulted in long-term developments that its original participants could never have foreseen, reshaping local environments and trade structures.`
      },
      {
        id: "hidden_connections",
        title: "Hidden Connections",
        content: `Underneath the obvious timelines, this event shares subtle, hidden threads with other domains. The mechanical, administrative, or artistic skills honed during this period directly fed into unrelated breakthroughs, illustrating the deeply interconnected nature of our shared historical canvas.`
      },
      {
        id: "modern_impact",
        title: "Modern Impact",
        content: `Today, we continue to live in the shockwave of this event. Our institutional frameworks, cultural habits, and technological dependencies are deeply marked by the choices made in ${node.date}, proving that history is not dead, but actively operating in the present.`
      }
    ];
  }
};
